## 微信机器人服务端配置
IP: 127.0.0.1
PORT: 5555

## 超级管理员配置
ADMINISTRATOR:
  - 'wxid_7bizfilssbwi22'

# ========================== 关键词配置信息 ========================== #
ADMIN_KEY_RESPONSE:         # 管理员关键词配置
  ADD_ADMIN:                # 添加管理员
    - '添加管理'
    - '添加管理员'
    - '增加管理员'
  DEL_ADMIN:                # 删除管理员
    - '删除管理'
    - '删除管理员'
    - '解除管理员'
  ADD_BLACK_GROUP:          # 添加黑名单群聊
    - '拉黑群聊'
    - '拉黑'
  DEL_BLACK_GROUP:          # 删除黑名单群聊
    - '解除拉黑'
    - '解除'
  ADD_PRIVILEGE_GROUP:      # 添加特权群聊
    - '新增群聊'
    - '添加群聊'
  DEL_PRIVILEGE_GROUP:      # 删除特权群聊
    - '删除群聊'
    - '解除群聊'
  REFRESH_CACHE:            # 清除缓存
    - '刷新缓存'
    - '清除缓存'
  SHOW_ADMINS:              # 查看所有管理员
    - '查看所有管理员'
    - '查看所有管理'
    - '查看管理'
  SHOW_PRIVILEGE_ROOMS:     # 查看所有特权群聊
    - '查看群聊'
    - '特权群聊'
  SHOW_BLACK_ROOMS:         # 查看所有黑名单群聊
    - '查看拉黑群聊'
    - '黑群'

KEY_RESPONSE:               # 功能关键词回复配置
  MORNING_PAPER:            # 配置早报关键词
    - '早报'
  EVENING_PAGE:             # 配置晚报关键词
    - '晚报'
    - '晚间咨询'
  SUFFIX:                   # 配置后缀查询关键词回复列表
    KEY1:                   # 配置第一个关键词
      - '后缀'
      - '后缀名'
    KEY2:                   # 配置第二个关键词
      - '查询'
      - '查找'
  ICP:                      # 配置备案查询关键词回复列表
    KEY1:
      - 'ICP'
      - 'icp'
      - '备案'
    KEY2:
      - '查询'
      - '查找'
  WHOIS:                    # 配置WHOIS查询关键词回复列表
    KEY1:
      - 'WHOIS'
      - 'whois'
    KEY2:
      - '查询'
      - '查看'
      - '查找'
  ASCRIPTION:               # 配置归属查询关键词回复列表
    KEY1:
      - '归属'
      - '归属地'
    KEY2:
      - '查询'
      - '查找'
      - '查看'
  GIRL_PIC:                   # 配置美女图片关键词回复列表
    - '照片'
    - '图片'
  GIRL_VIDEO:                 # 配置美女视频关键词回复列表
    - '视频'
    - '美女视频'
  LICK_DOG:                   # 配置舔狗日记关键词回复列表
    - '舔狗日记'
    - '舔狗'
  TOUCH_FISH:                 # 配置摸鱼日记关键词回复列表
    - '摸鱼日记'
    - '摸鱼日历'
  MORNING_MESSAGE:            # 配置早安寄语关键词回复列表
    - '早安寄语'
    - '早安'
  HOROSCOPE:                  # 配置星座查询关键词回复字典
    KEY1:
      - '查询'
      - '查看'
      - '查找'
    KEY2:
      - '运势'
      - '气运'
  WETHER:                     # 配置天气查询关键词回复列表
    KEY1:
      - '天气'
      - '气候'
      - '气温'
      - '天象'
    KEY2:
      - '查询'
      - '查找'
      - '查看'
  QUERY_ICP:                  # 配置ICP查询关键词回复列表
    key1:
      - 'icp'
      - 'ICP'
      - '备案'
    key2:
      - '查询'
      - '查找'
  THREAT_BOOK:                # 配置微步威胁情报查询
    KEY1:
      - 'IP'
      - 'ip'
      - '微步'
    KEY2:
      - '查询'
      - '查找'
  HELP:                       # 配置帮助关键词回复列表
    - '帮助'
    - 'help'
    - 'HELP'

CUSTOM_KEYWORD_REPLY:         # 自定义关键词回复配置
  大牛博客: 'ngc660.cn'
  小牛博客: 'ngc660.com'

INTEGRAL_CONFIG:              # 积分相关配置
  SIGN_KEY:                   # 签到口令
    - '签到：NGC660安全实验室祝大家天天得0day!'
  SIGN_INTEGRAL: 10           # 签到积分
  ADD_INTEGRAL:               # 增加积分关键词配置
    - '+'
    - '加'
  DEL_INTEGRAL:               # 扣除积分关键词配置
    - '-'
    - '减'
  QUERY_INTEGRAL:             # 积分查询配置
    - '积分查询'
    - '查询积分'
  ATTRIBUTION_POINT: 2        # 归属地积分查询配置
  WHOIS_POINT: 3              # WHOIS积分查询配置
  ICP_POINT: 4                # 备案查询积分配置
  EXTENSIONS_POINT: 3         # 后缀名查询积分配置
  THREATBOOK_POINT: 5         # 微步情报查询积分配置

MESSAGE_CONFIGURATION:        # 系统消息配置
  JOIN_ROOM_MESSAGE: '欢迎{}加入群聊'            # 新人入群消息配置
  COPYRIGHT_MESSAGE: 'NGC660安全实验室'         # 配置版权信息
  OFF_WORK_MESSAGE: '各部门请注意，下班时间已到！！！请滚，不要浪费电费，记得发日报！\n[Doge] over'     # 配置下班通知

# ========================== 关键词配置信息 END========================== #


# ========================== 定时推送配置 ========================== #
# 注意： 8:03 必须写 08:03 否则不执行
TIME_MORNING: '08:30'         # 早报自动推送时间
TIME_EVENING: '17:00'         # 晚间咨询推送时间
TIME_FISH: '09:30'            # 摸鱼日历推送时间
TIME_AFTER: '18:00'           # 下班时间

# ========================== 定时推送配置 END ========================== #


# ========================== 配置各类API接口信息 ========================== #

GIRL_VIDEO_URLS:                # 美女视频地址
  - 'https://tucdn.wpon.cn/api-girl/'
  - 'https://v.api.aa1.cn/api/api-dy-girl/index.php?aa1=json'

GIRL_PIC_URLS:                  # 美女图片地址
  - 'https://api.vvhan.com/api/girl'
  - 'https://v.api.aa1.cn/api/pc-girl_bz/index.php?wpon=ro38d57y8rhuwur3788y3rd'
  - 'https://api.vvhan.com/api/mobil.girl'
  - 'https://api.vvhan.com/api/girl'
  - 'https://api.vvhan.com/api/tao'

# 小爱AI对话接口
XIAOAI_URL: 'https://v.api.aa1.cn/api/api-xiaoai/talk.php?msg={}&type=text'

# 摸鱼日历接口地址
TOUCH_FISH_CALENDAR: 'https://api.vvhan.com/api/moyu'

# 归属地查询地址
ATTRIBUTION_URL: 'https://v.api.aa1.cn/api/phone/guishu-api.php?phone={}'

# WHOIS查询地址
WHOIS_URL: 'https://v.api.aa1.cn/api/whois/index.php?domain={}'

# ICP查询地址
ICP_URL: 'https://v.api.aa1.cn/api/icp/index.php?url={}'

# 微步URL地址
THREATBOOK_URL: 'https://api.threatbook.cn/v3/scene/ip_reputation'

# 微步社区KEY
THREATBOOK_KEY: '6518ffbfade84bc1a01718f595cefedb23fa2924b51842978b7e0b5a13b02827'

# ========================== 配置各类API接口信息  END========================== #



# ========================== 安全咨询地址配置 ========================== #
XZ_URL: 'https://xz.aliyun.com/feed'
FREEBUF_URL: 'https://www.freebuf.com/feed'
QAX_URL: 'https://forum.butian.net/Rss'
ANQUANKE_URL: 'https://www.anquanke.com/knowledge'

# ========================== 安全咨询地址配置  END========================== #


# ========================== 天行API通用配置 ========================== #
# 全局通用APPID
APPID: '45279436'
# 全局通用APPSECRET
APPSECRET: 'lohAjD4R'
# 全局通用KEY
KEY: 'e8409cd6401b93d170297440ace30f27'
# 天气查询接口
WEATHER_URL: 'https://www.tianqiapi.com/free/day?appid={}&appsecret={}&city={}'
# 舔狗日记接口
LICK_DOG_URL: 'http://api.tianapi.com/tiangou/index?key={}'
# 星座运势接口
HOROSCOPE_URL: 'http://api.tianapi.com/star/index?key={}&astro={}'
# 早安寄语接口
GOOD_MORNING_MESSAGE_URL: 'https://apis.tianapi.com/zaoan/index?key={}'
# 扩展名查询接口
EXTENSIONS_URL: 'https://apis.tianapi.com/targa/index?key={}&word={}'

# ========================== 天行API通用配置 END ========================== #
